"""Real-time chunking (RTC) policy execution.

Implements Algorithm 1 from "Real-Time Execution of Action Chunking Flow
Policies" (Black et al., 2025). The controller calls :meth:`infer` once per
control tick. Model inference runs concurrently in a background thread while
the current action chunk continues to execute.
"""

from __future__ import annotations

from collections import deque
import dataclasses
import logging
import threading
import time
from typing import TYPE_CHECKING, Any

import numpy as np
from openpi_client import base_policy as _base_policy
from typing_extensions import override

if TYPE_CHECKING:
    from openpi.policies import policy as _policy

logger = logging.getLogger(__name__)


@dataclasses.dataclass(frozen=True)
class RTCConfig:
    """Inference-time configuration from Algorithm 1 of the RTC paper."""

    enabled: bool = False
    # None adapts to the model horizon: H // 2 (25 for the paper's H=50,
    # 8 for the common UMI H=16 configuration).
    min_execution_horizon: int | None = None
    # None uses min(6, H // 4): 6 for H=50 and 4 for UMI H=16.
    initial_delay_steps: int | None = None
    delay_buffer_size: int = 10
    num_steps: int = 5
    guidance_weight: float = 5.0


def make_soft_mask(*, horizon: int, delay: int, execution_horizon: int) -> np.ndarray:
    """Compute the exponentially decaying RTC mask from paper Equation 5."""
    if horizon <= 0:
        raise ValueError(f"horizon must be positive, got {horizon}")
    if not 0 <= delay <= execution_horizon:
        raise ValueError(f"RTC requires 0 <= delay <= execution_horizon, got {delay} and {execution_horizon}")
    if execution_horizon > horizon - delay:
        raise ValueError(
            f"RTC requires execution_horizon <= horizon - delay, got {execution_horizon} > {horizon - delay}"
        )

    indices = np.arange(horizon, dtype=np.float32)
    overlap = horizon - execution_horizon
    denominator = overlap - delay + 1
    c = (overlap - indices) / denominator
    decay = np.square(c) * np.expm1(c) / np.expm1(1.0)
    return np.where(indices < delay, 1.0, np.where(indices < overlap, decay, 0.0)).astype(np.float32)


class RealTimeChunkingPolicy(_base_policy.BasePolicy):
    """Serve one action per tick while generating guided chunks asynchronously.

    The first call blocks to create the initial action chunk. Every later call
    returns immediately from the currently available chunk. Once at least
    ``min_execution_horizon`` actions have elapsed, a worker thread starts the
    next guided inference using the latest observation.
    """

    def __init__(self, policy: _policy.Policy, config: RTCConfig):
        if not config.enabled:
            raise ValueError("RealTimeChunkingPolicy requires RTCConfig.enabled=True")
        if not policy.supports_rtc:
            raise ValueError("RTC is only supported by flow-based pi0/pi0.5 policies")
        if config.delay_buffer_size <= 0:
            raise ValueError("delay_buffer_size must be positive")
        if config.num_steps <= 0:
            raise ValueError("num_steps must be positive")
        if config.guidance_weight <= 0:
            raise ValueError("guidance_weight must be positive")

        horizon = policy.action_horizon
        config = dataclasses.replace(
            config,
            min_execution_horizon=(
                config.min_execution_horizon if config.min_execution_horizon is not None else max(1, horizon // 2)
            ),
            initial_delay_steps=(
                config.initial_delay_steps if config.initial_delay_steps is not None else min(6, horizon // 4)
            ),
        )
        assert config.min_execution_horizon is not None
        assert config.initial_delay_steps is not None

        make_soft_mask(
            horizon=horizon,
            delay=config.initial_delay_steps,
            execution_horizon=config.min_execution_horizon,
        )

        self._policy = policy
        self._config = config
        self._condition = threading.Condition()
        self._delay_steps = deque([config.initial_delay_steps], maxlen=config.delay_buffer_size)
        self._current_result: dict[str, Any] | None = None
        self._latest_obs: dict[str, Any] | None = None
        self._step = 0
        self._inference_active = False
        self._worker_error: BaseException | None = None
        self._stop = False
        self._worker: threading.Thread | None = None
        self._last_inference_ms = 0.0

    @override
    def infer(self, obs: dict) -> dict:  # type: ignore[misc]
        # A_init in Algorithm 1. Startup is the only inference that blocks the
        # controller; all subsequent chunks are generated by the worker.
        with self._condition:
            if self._current_result is None:
                self._current_result = self._policy.infer(obs)
                self._warmup_guided_inference(obs)
                self._worker = threading.Thread(target=self._inference_loop, name="openpi-rtc", daemon=True)
                self._worker.start()

            if self._worker_error is not None:
                raise RuntimeError("RTC background inference failed") from self._worker_error

            self._latest_obs = obs
            self._step += 1
            action_index = self._step - 1
            actions = np.asarray(self._current_result["actions"])
            if action_index >= len(actions):
                raise RuntimeError(
                    "RTC exhausted the current action chunk before background inference completed. "
                    "Increase the model action horizon, lower min_execution_horizon, or reduce inference latency."
                )

            result = dict(self._current_result)
            # Preserve chunk-shaped server responses so existing clients work
            # with ActionChunkBroker(action_horizon=1).
            result["actions"] = actions[action_index : action_index + 1]
            result["rtc_timing"] = {
                "step": self._step,
                "predicted_delay_steps": max(self._delay_steps),
                "inference_active": self._inference_active,
                "last_infer_ms": self._last_inference_ms,
            }
            self._condition.notify_all()
            return result

    def _warmup_guided_inference(self, obs: dict) -> None:
        """Compile the guided path before real-time execution begins."""
        warmup = getattr(self._policy, "warmup_rtc", None)
        if warmup is None:
            return
        previous_actions = self._policy.last_model_actions
        if previous_actions is None:
            raise RuntimeError("RTC policy did not retain its initial normalized action chunk")
        execution_horizon = self._config.min_execution_horizon
        overlap = self._policy.action_horizon - execution_horizon
        target = np.zeros_like(previous_actions)
        target[:overlap] = previous_actions[execution_horizon:]
        mask = make_soft_mask(
            horizon=self._policy.action_horizon,
            delay=self._config.initial_delay_steps,
            execution_horizon=execution_horizon,
        )
        warmup(
            obs,
            rtc_actions=target,
            rtc_mask=mask,
            rtc_guidance_weight=self._config.guidance_weight,
        )

    def _inference_loop(self) -> None:
        while True:
            with self._condition:
                self._condition.wait_for(
                    lambda: (
                        self._stop
                        or self._worker_error is not None
                        or (self._step >= self._config.min_execution_horizon and not self._inference_active)
                    )
                )
                if self._stop or self._worker_error is not None:
                    return

                execution_horizon = self._step
                predicted_delay = max(self._delay_steps)
                try:
                    mask = make_soft_mask(
                        horizon=self._policy.action_horizon,
                        delay=predicted_delay,
                        execution_horizon=execution_horizon,
                    )
                    previous_actions = self._policy.last_model_actions
                    if previous_actions is None:
                        raise RuntimeError("RTC policy did not retain its previous normalized action chunk")
                    target = np.zeros_like(previous_actions)
                    overlap = self._policy.action_horizon - execution_horizon
                    target[:overlap] = previous_actions[execution_horizon:]
                    observation = self._latest_obs
                    if observation is None:
                        raise RuntimeError("RTC inference started without an observation")
                    self._inference_active = True
                except Exception as error:
                    self._worker_error = error
                    self._condition.notify_all()
                    return

            started = time.monotonic()
            try:
                new_result = self._policy.infer(
                    observation,
                    rtc_actions=target,
                    rtc_mask=mask,
                    rtc_guidance_weight=self._config.guidance_weight,
                )
            except Exception as error:
                with self._condition:
                    self._worker_error = error
                    self._inference_active = False
                    self._condition.notify_all()
                return

            elapsed_ms = (time.monotonic() - started) * 1000
            with self._condition:
                # Calls to infer that occurred while the model was running are
                # the observed delay t in Algorithm 1, independent of wall time.
                observed_delay = self._step - execution_horizon
                self._current_result = new_result
                self._step -= execution_horizon
                self._delay_steps.append(observed_delay)
                self._last_inference_ms = elapsed_ms
                self._inference_active = False
                logger.debug(
                    "RTC swapped chunks (s=%d, predicted d=%d, observed d=%d, %.1f ms)",
                    execution_horizon,
                    predicted_delay,
                    observed_delay,
                    elapsed_ms,
                )
                self._condition.notify_all()

    @property
    def metadata(self) -> dict[str, Any]:
        return {
            **self._policy.metadata,
            "rtc": dataclasses.asdict(self._config),
            "action_horizon": 1,
        }

    @override
    def reset(self) -> None:
        with self._condition:
            self._stop = True
            self._condition.notify_all()
            worker = self._worker
        if worker is not None and worker is not threading.current_thread():
            worker.join()

        self._policy.reset()
        with self._condition:
            self._delay_steps = deque([self._config.initial_delay_steps], maxlen=self._config.delay_buffer_size)
            self._current_result = None
            self._latest_obs = None
            self._step = 0
            self._inference_active = False
            self._worker_error = None
            self._stop = False
            self._worker = None
            self._last_inference_ms = 0.0
